name: presentation-types
version: '0.1.0.0'
category: Embedded
author: Scott Murphy
maintainer: scottmurphy09@gmail.com
copyright: MIT License
license: BSD3
github: smurphy8/presentation-types
extra-source-files:
- README.md

dependencies:
  - base >=4.7 && <5
  - aeson
  - servant
  - time  
library:
  source-dirs: src
  exposed-modules:
  - Presentation.Typeso
  ghc-options:
    - -Wall
tests:
  presentation-types-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - presentation-types
    - hspec
    - hspec-wai
    - hspec-wai-json
    - servant-aeson-specs
    - QuickCheck
    - quickcheck-arbitrary-adt
    - aeson
