name: presentation-server
version: '0.1.0.0'
category: Embedded
author: Scott Murphy
maintainer: scottmurphy09@gmail.com
copyright: MIT License
license: BSD3
github: smurphy8/presentation-server
extra-source-files:
- README.md
dependencies:
  - time
  - base >=4.7 && <5
  - aeson
  - servant-server
  - trifecta  
  - presentation-types
  - wai
  - warp
library:
  source-dirs: src
  exposed-modules:
  - Server
  dependencies:

  ghc-options:
    - -Wall
executables:
  presentation-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - presentation-server
tests:
  presentation-server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - presentation-server
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
